[green_agent]
agentbeats_id = "019bc5cc-c93e-7372-ad04-ec1115efe810"
env = {RAPID_API_KEY = "${RAPID_API_KEY}", OPENAI_API_KEY = "${OPENAI_API_KEY}", OPENAI_BASE_URL = "${OPENAI_BASE_URL}", EVAL_MODEL = "${EVAL_MODEL}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019bc5c2-b952-7941-ac94-4cd2c3077292" # set your own purple agent here
name = "agent"
env = {OPENAI_API_KEY = "${OPENAI_API_KEY}", OPENAI_BASE_URL = "${OPENAI_BASE_URL}", OPENAI_MODEL = "${OPENAI_MODEL}"}


# [config]
## Add your assessment config here
# benchmark = "bfcl" # available benchmarks: bfcl, tau2 and cfb
# test_category = "simple_python"
# num_tasks=10

[config]
# Add your assessment config here
benchmark = "tau2" # available benchmarks: bfcl, tau2 and cfb
domain = "retail"
num_tasks=10

# [config]
## Add your assessment config here
# benchmark = "cfb" # available benchmarks: bfcl, tau2 and cfb
# num_tasks=10